import { useEffect, useState } from 'react'
import { CreditCard, ExternalLink } from 'lucide-react'
import { Alert, Badge, Button, PageHeader, Panel } from '../../../shared/components'
import { suscripcionesApi, type Consumption, type Plan, type Subscription } from '../api/suscripcionesApi'

function Usage({ label, used, limit }: { label: string; used: number; limit: number }) { const percent = Math.min(100, Math.round((used / limit) * 100)); return <div className="usage-row"><div><strong>{label}</strong><span>{used} de {limit}</span></div><progress max="100" value={percent}>{percent}%</progress></div> }

export function MiSuscripcionPage() {
  const [subscription, setSubscription] = useState<Subscription | null>(null); const [usage, setUsage] = useState<Consumption | null>(null); const [plans, setPlans] = useState<Plan[]>([]); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  useEffect(() => { Promise.all([suscripcionesApi.current(), suscripcionesApi.consumption(), suscripcionesApi.plans()]).then(([s, u, p]) => { setSubscription(s); setUsage(u); setPlans(p) }).catch((e: Error) => setMessage(e.message)) }, [])
  async function redirect(action: () => Promise<{ url: string }>) { setBusy(true); try { const result = await action(); window.location.assign(result.url) } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo abrir Stripe.') } finally { setBusy(false) } }
  return <section className="page-stack"><PageHeader eyebrow="Facturación" title="Mi suscripción" description="Consulta el plan, su vigencia y el consumo actual de tu empresa." />{message && <Alert tone="error">{message}</Alert>}{subscription && <><Panel title={subscription.plan.nombre} count={<Badge tone={subscription.estado === 'ACTIVA' ? 'success' : 'warning'}>{subscription.estado}</Badge>}><div className="subscription-summary"><div><span>Precio mensual</span><strong>{subscription.plan.precio_mensual} {subscription.plan.moneda}</strong></div><div><span>Próximo cobro</span><strong>{subscription.fecha_proximo_cobro ? new Date(subscription.fecha_proximo_cobro).toLocaleDateString('es-BO') : 'Sin programar'}</strong></div><div><span>Módulos</span><strong>{subscription.plan.modulos.length}</strong></div></div><Button variant="secondary" loading={busy} disabled={!subscription.stripe_customer_id} onClick={() => void redirect(suscripcionesApi.portal)}><ExternalLink size={16} />Administrar pago</Button></Panel>{usage && <Panel title="Consumo del plan"><div className="usage-list"><Usage label="Usuarios activos" used={usage.usuarios.usado} limit={usage.usuarios.limite} /><Usage label="Vacantes activas" used={usage.vacantes_activas.usado} limit={usage.vacantes_activas.limite} /><Usage label="Almacenamiento MB" used={usage.almacenamiento_mb.usado} limit={usage.almacenamiento_mb.limite} /></div></Panel>}<Panel title="Planes disponibles"><div className="card-grid">{plans.map((plan) => <article className="card" key={plan.id}><h3>{plan.nombre}</h3><p>{plan.descripcion}</p><strong>{plan.precio_mensual} {plan.moneda}/mes</strong><small>{plan.max_usuarios} usuarios · {plan.max_vacantes_activas} vacantes</small><Button disabled={plan.id === subscription.plan.id} loading={busy} onClick={() => void redirect(() => suscripcionesApi.checkout(plan.id))}><CreditCard size={16} />{plan.id === subscription.plan.id ? 'Plan actual' : 'Elegir plan'}</Button></article>)}</div></Panel></>}</section>
}
