import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { CreditCard, Pencil, Plus } from 'lucide-react'
import { empresasApi } from '../../empresas/api/empresasApi'
import { modulosApi, type Modulo } from '../../empresas/api/modulosApi'
import { Alert, Badge, Button, Field, PageHeader, Panel, type BadgeTone } from '../../../shared/components'
import { suscripcionesApi, type Plan, type PlanInput, type Subscription } from '../api/suscripcionesApi'

const STATUS_TONE: Record<string, BadgeTone> = { ACTIVA: 'success', PRUEBA: 'info', PENDIENTE: 'warning', VENCIDA: 'warning', PAGO_FALLIDO: 'danger', SUSPENDIDA: 'danger', CANCELADA: 'neutral' }
type CompanySubscription = { id: string; nombre: string; subscription: Subscription | null }

const empty: PlanInput = { nombre: '', descripcion: '', precio_mensual: '0', moneda: 'USD', max_usuarios: 5, max_vacantes_activas: 5, max_almacenamiento_mb: 250, stripe_price_id: null, modulos: [], activo: true }

export function PlanesPage() {
  const [plans, setPlans] = useState<Plan[]>([]); const [modules, setModules] = useState<Modulo[]>([])
  const [form, setForm] = useState<PlanInput>(empty); const [editing, setEditing] = useState<string | null>(null)
  const [companies, setCompanies] = useState<Array<{ id: string; nombre_comercial: string }>>([])
  const [companyId, setCompanyId] = useState(''); const [planId, setPlanId] = useState('')
  const [subscriptionStatus, setSubscriptionStatus] = useState('ACTIVA')
  const [subscriptions, setSubscriptions] = useState<CompanySubscription[] | null>(null)
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const load = useCallback(async () => { const [p, m, c] = await Promise.all([suscripcionesApi.plans(true), modulosApi.catalogo(), empresasApi.list({ per_page: 100 })]); setPlans(p); setModules(m); setCompanies(c.items); setPlanId((current) => current || p[0]?.id || ''); await loadSubscriptions(c.items) }, [])
  /** No hay listado global en el backend: se consulta la suscripción de cada empresa; un 404 significa que aún no tiene plan. */
  async function loadSubscriptions(items: Array<{ id: string; nombre_comercial: string }>) {
    const rows = await Promise.all(items.map(async (c) => ({ id: c.id, nombre: c.nombre_comercial, subscription: await suscripcionesApi.current(c.id).catch(() => null) })))
    setSubscriptions(rows.sort((a, b) => a.nombre.localeCompare(b.nombre)))
  }
  useEffect(() => { void load().catch((e: Error) => setMessage(e.message)) }, [load])
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { if (editing) await suscripcionesApi.updatePlan(editing, form); else await suscripcionesApi.createPlan(form); setForm(empty); setEditing(null); setMessage('Plan guardado correctamente.'); await load() } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo guardar.') } finally { setBusy(false) } }
  async function assign() { if (!companyId || !planId) return; if (['SUSPENDIDA', 'CANCELADA'].includes(subscriptionStatus) && !window.confirm(`¿Confirmas dejar la suscripción ${subscriptionStatus.toLowerCase()}?`)) return; setBusy(true); try { await suscripcionesApi.assign(companyId, planId, subscriptionStatus); setMessage('Suscripción asignada y módulos sincronizados.'); await loadSubscriptions(companies) } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo asignar.') } finally { setBusy(false) } }
  function edit(plan: Plan) { setEditing(plan.id); setForm({ nombre: plan.nombre, descripcion: plan.descripcion, precio_mensual: plan.precio_mensual, moneda: plan.moneda, max_usuarios: plan.max_usuarios, max_vacantes_activas: plan.max_vacantes_activas, max_almacenamiento_mb: plan.max_almacenamiento_mb, stripe_price_id: plan.stripe_price_id, modulos: plan.modulos, activo: plan.activo }) }
  return <section className="page-stack"><PageHeader eyebrow="Administración SaaS" title="Planes y suscripciones" description="Configura precios, capacidades y módulos contratables para todas las empresas." />{message && <Alert tone="info">{message}</Alert>}
    <Panel title={editing ? 'Editar plan' : 'Nuevo plan'} eyebrow="Catálogo global"><form onSubmit={save}><div className="form-grid"><Field label="Nombre"><input required value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} /></Field><Field label="Descripción"><input value={form.descripcion ?? ''} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} /></Field><Field label="Precio mensual"><input required type="number" min="0" step="0.01" value={form.precio_mensual} onChange={(e) => setForm({ ...form, precio_mensual: e.target.value })} /></Field><Field label="Moneda"><input required maxLength={3} value={form.moneda} onChange={(e) => setForm({ ...form, moneda: e.target.value.toUpperCase() })} /></Field><Field label="Usuarios"><input type="number" min="1" value={form.max_usuarios} onChange={(e) => setForm({ ...form, max_usuarios: Number(e.target.value) })} /></Field><Field label="Vacantes activas"><input type="number" min="1" value={form.max_vacantes_activas} onChange={(e) => setForm({ ...form, max_vacantes_activas: Number(e.target.value) })} /></Field><Field label="Almacenamiento MB"><input type="number" min="1" value={form.max_almacenamiento_mb} onChange={(e) => setForm({ ...form, max_almacenamiento_mb: Number(e.target.value) })} /></Field><Field label="Stripe Price ID"><input placeholder="price_..." value={form.stripe_price_id ?? ''} onChange={(e) => setForm({ ...form, stripe_price_id: e.target.value || null })} /></Field></div><Field label="Módulos incluidos"><div className="check-grid">{modules.map((m) => <label className="check-label" key={m.id}><input type="checkbox" checked={form.modulos.includes(m.codigo)} onChange={() => setForm({ ...form, modulos: form.modulos.includes(m.codigo) ? form.modulos.filter((x) => x !== m.codigo) : [...form.modulos, m.codigo] })} />{m.nombre}</label>)}</div></Field><label className="check-label"><input type="checkbox" checked={form.activo} onChange={(e) => setForm({ ...form, activo: e.target.checked })} />Plan disponible</label><div className="form-actions"><Button type="submit" loading={busy}><Plus size={16} aria-hidden="true" />{editing ? 'Guardar cambios' : 'Crear plan'}</Button>{editing && <Button variant="secondary" onClick={() => { setEditing(null); setForm(empty) }}>Cancelar</Button>}</div></form></Panel>
    <Panel title="Catálogo" count={`${plans.length} planes`}><div className="card-grid">{plans.map((plan) => <article className="card" key={plan.id}><div className="panel-heading"><h3>{plan.nombre}</h3><Badge tone={plan.activo ? 'success' : 'neutral'}>{plan.activo ? 'ACTIVO' : 'INACTIVO'}</Badge></div><p>{plan.descripcion}</p><strong className="plan-price">{plan.precio_mensual} {plan.moneda}/mes</strong><small>{plan.max_usuarios} usuarios · {plan.max_vacantes_activas} vacantes · {plan.max_almacenamiento_mb} MB</small><Button variant="secondary" size="sm" onClick={() => edit(plan)}><Pencil size={15} />Editar</Button></article>)}</div></Panel>
    <Panel title="Suscripciones por empresa" count={subscriptions ? `${subscriptions.length} empresas` : undefined}>{subscriptions === null ? <p>Cargando suscripciones…</p> : subscriptions.length === 0 ? <p>No hay empresas registradas.</p> : <div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Plan</th><th>Estado</th><th>Próximo cobro</th></tr></thead><tbody>{subscriptions.map((row) => <tr key={row.id}><td><strong>{row.nombre}</strong></td><td>{row.subscription ? `${row.subscription.plan.nombre} · ${row.subscription.plan.precio_mensual} ${row.subscription.plan.moneda}/mes` : 'Sin plan'}</td><td>{row.subscription ? <Badge tone={STATUS_TONE[row.subscription.estado] ?? 'neutral'}>{row.subscription.estado.replaceAll('_', ' ')}</Badge> : <Badge>SIN SUSCRIPCIÓN</Badge>}</td><td>{row.subscription?.fecha_proximo_cobro ? new Date(row.subscription.fecha_proximo_cobro).toLocaleDateString('es-BO') : '—'}</td></tr>)}</tbody></table></div>}</Panel>
    <Panel title="Asignación manual" eyebrow="Soporte de plataforma"><div className="backup-create-row"><Field label="Empresa"><select value={companyId} onChange={(e) => setCompanyId(e.target.value)}><option value="">Seleccionar</option>{companies.map((c) => <option key={c.id} value={c.id}>{c.nombre_comercial}</option>)}</select></Field><Field label="Plan"><select value={planId} onChange={(e) => setPlanId(e.target.value)}>{plans.filter((p) => p.activo).map((p) => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></Field><Field label="Estado"><select value={subscriptionStatus} onChange={(e) => setSubscriptionStatus(e.target.value)}>{['PRUEBA', 'PENDIENTE', 'ACTIVA', 'VENCIDA', 'PAGO_FALLIDO', 'SUSPENDIDA', 'CANCELADA'].map((status) => <option key={status} value={status}>{status}</option>)}</select></Field><Button loading={busy} onClick={() => void assign()}><CreditCard size={16} aria-hidden="true" />Aplicar</Button></div></Panel>
  </section>
}
